Name-Shivani Goyal

In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_movies.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
movies=movies.merge(credits,on='title')

In [6]:
movies.head(1)

,budget_x,genres_x,homepage_x,id_x,keywords_x,original_language_x,original_title_x,overview_x,popularity_x,production_companies_x,...,production_companies_y,production_countries_y,release_date_y,revenue_y,runtime_y,spoken_languages_y,status_y,tagline_y,vote_average_y,vote_count_y
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,7.2,11800

In [7]:
# Important columns
# genre , id , keywords , title , overview ,  cast , crew

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 39 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   budget_x                4809 non-null   int64
 1   genres_x                4809 non-null   object
 2   homepage_x              1713 non-null   object
 3   id_x                    4809 non-null   int64
 4   keywords_x              4809 non-null   object
 5   original_language_x     4809 non-null   object
 6   original_title_x        4809 non-null   object
 7   overview_x              4806 non-null   object
 8   popularity_x            4809 non-null   float64
 9   production_companies_x  4809 non-null   object
 10  production_countries_x  4809 non-null   object
 11  release_date_x          4808 non-null   object
 12  revenue_x               4809 non-null   int64
 13  runtime_x               4807 non-null   float64
 14  spoken_languages_x      4809 non-null   object
 15  status_x                4809 non-null   object
 16  tagline_x               3965 non-null   object
 17  title                   4809 non-null   object
 18  vote_average_x          4809 non-null   float64
 19  vote_count_x            4809 non-null   int64
 20  budget_y                4809 non-null   int64
 21  genres_y                4809 non-null   object
 22  homepage_y              1713 non-null   object
 23  id_y                    4809 non-null   int64
 24  keywords_y              4809 non-null   object
 25  original_language_y     4809 non-null   object
 26  original_title_y        4809 non-null   object
 27  overview_y              4806 non-null   object
 28  popularity_y            4809 non-null   float64
 29  production_companies_y  4809 non-null   object
 30  production_countries_y  4809 non-null   object
 31  release_date_y          4808 non-null   object
 32  revenue_y               4809 non-null   int64
 33  runtime_y               4807 non-null   float64
 34  spoken_languages_y      4809 non-null   object
 35  status_y                4809 non-null   object
 36  tagline_y               3965 non-null   object
 37  vote_average_y          4809 non-null   float64
 38  vote_count_y            4809 non-null   int64
dtypes: float64(6), int64(8), object(25)
memory usage: 1.5+ MB

In [9]:
movies=movies[['id_x' ,'title' ,'overview_x' , 'genres_x','keywords_x']]

In [10]:
movies.head(1)

,id_x,title,overview_x,genres_x,keywords_x
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."

In [11]:
movies.isnull().sum()

id_x          0
title         0
overview_x    3
genres_x      0
keywords_x    0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [13]:
movies.isnull().sum()

id_x          0
title         0
overview_x    0
genres_x      0
keywords_x    0
dtype: int64

In [14]:
movies.duplicated().sum()

6

In [15]:
movies.drop_duplicates(inplace=True)

In [16]:
movies.duplicated().sum()

0

In [17]:
movies.iloc[0].genres_x

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [18]:
import ast
ast.literal_eval
def convert(obj):
    list=[]
    for i in ast.literal_eval(obj):
        list.append(i['name'])
    return list

In [19]:
movies['genres_x']=movies['genres_x'].apply(convert)

In [20]:
movies.head(1)

,id_x,title,overview_x,genres_x,keywords_x
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."

In [21]:
movies['keywords_x']=movies['keywords_x'].apply(convert)

In [22]:
movies.head()

,id_x,title,overview_x,genres_x,keywords_x
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [23]:
movies['overview_x']=movies['overview_x'].apply(lambda x:x.split())

In [24]:
movies.head()

,id_x,title,overview_x,genres_x,keywords_x
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [25]:
movies['genres_x']=movies['genres_x'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords_x']=movies['keywords_x'].apply(lambda x:[i.replace(" ","")for i in x])

In [26]:
movies.head()

,id_x,title,overview_x,genres_x,keywords_x
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p..."

In [27]:
movies['tags']=movies['overview_x']+movies['genres_x']+movies['keywords_x']

In [28]:
movies.head()

,id_x,title,overview_x,genres_x,keywords_x,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili..."

In [29]:
new_data=movies[['id_x','title','tags']]

In [30]:
new_data

,id_x,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [31]:
new_data['tags']=new_data['tags'].apply(lambda x:" ".join(x))

C:\Users\HP\AppData\Local\Temp/ipykernel_8456/2257165486.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tags']=new_data['tags'].apply(lambda x:" ".join(x))

In [32]:
new_data.head()

,id_x,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [33]:
new_data['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d'

In [34]:
new_data['tags']=new_data['tags'].apply(lambda x:x.lower())

C:\Users\HP\AppData\Local\Temp/ipykernel_8456/3760292952.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tags']=new_data['tags'].apply(lambda x:x.lower())

In [35]:
new_data.head()

,id_x,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [36]:
new_data['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d'

In [37]:
new_data['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger"

In [38]:
#stemming
import nltk

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [39]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [40]:
def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [41]:
new_data['tags']=new_data['tags'].apply(stem)

C:\Users\HP\AppData\Local\Temp/ipykernel_8456/2662728569.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tags']=new_data['tags'].apply(stem)

In [42]:
new_data['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d'

In [43]:
#Text Vectorization - Bag of words technique

In [44]:
#stopword removal
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [45]:
vectors=cv.fit_transform(new_data['tags']).toarray()

In [46]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [47]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [48]:
len(cv.get_feature_names())

5000

In [49]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '150',
 '16',
 '17',
 '17th',
 '18',
 '1890',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1976',
 '1979',
 '1980',
 '1980s',
 '1985',
 '1990',
 '1995',
 '1997',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2000',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '80',
 'aaron',
 'abandon',
 'abbi',
 'abduct',
 'abil',
 'abl',
 'aboard',
 'aborigin',
 'abov',
 'abroad',
 'absolut',
 'absurd',
 'abus',
 'academ',
 'academi',
 'academy',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'acquir',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrift',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'adults',
 'advanc',
 'advantag',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'affluent',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'ail',
 'aim',
 'air',
 'airborn',
 'aircraft',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alcoholabus',
 'alex',
 'algeria',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'alleg',
 'allen',
 'alli',
 'allianc',
 'allies',
 'allow',
 'alon',
 'alongsid',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientgreec',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andrew',
 'android',
 'andy',
 'angel',
 'angela',
 'angeles',
 'anger',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'ann',
 'anna',
 'annabel',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antarct',
 'antholog',
 'anthoni',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appli',
 'appoint',
 'appreci',
 'apprehend',
 'apprentic',
 'approach',
 'approaches',
 'april',
 'aquarium',
 'arab',
 'arbitrarylaw',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arizona',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arrang',
 'arrangedmarriag',
 'array',
 'arrest',
 'arriv',
 'arrives',
 'arrog',
 'arson',
 'art',
 'artgalleri',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'artists',
 'ash',
 'ashley',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atlant',
 'atlanta',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attemptedmurd',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austria',
 'author',
 'autism',
 'auto',
 'autobiograph',
 'automobilerac',
 'avail',
 'aveng',
 'averag',
 'aviat',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awesom',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'backyard',
 'bad',
 'bag',
 'bahama',
 'bail',
 'baker',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbara',
 'barbarian',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrier',
 'barry',
 'bas',
 'base',
 'basebal',
 'basedonchildren',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'bathtub',
 'batman',
 'battalion',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'beg',
 'began',
 'begin',
 'begins',
 'behavior',
 'behead',
 'belgium',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'bend',
 'beneath',
 'benefit',
 'benjamin',
 'bennett',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'betrayal',
 'better',
 'betti',
 'beverli',
 'bibl',
 'biblic',
 'bicker',
 'bicycl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'bilbo',
 'billi',
 'billion',
 'billionair',
 'biograph',
 'biographi',
 'biolog',
 'biopic',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bittersweet',
 'bizarr',
 'black',
 'blackandwhit',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blast',
 'blaze',
 'blend',
 'bless',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blog',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'bloom',
 'blossom',
 'blow',
 'blu',
 'blue',
 'blunt',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'borrow',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'bowl',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brent',
 'brian',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brood',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brutal',
 'bu',
 'buck',
 'bud',
 'budapest',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bum',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'businesswoman',
 'bust',
 'butch',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cain',
 'cairo',
 'cal',
 'caleb',
 'california',
 'calm',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camp',
 'campaign',
 'campbel',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'candlelightvigil',
 'canin',
 'cannabi',
 'cannib',
 'canuxploit',
 'canyon',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'cargo',
 'caribbean',
 'carjourney',
 'carl',
 'carlo',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'cartel',
 'carter',
 'cartoon',
 'case',
 'cash',
 'casino',
 'cast',
 'castl',
 'castle',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'catherin',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cause',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'ceremoni',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channel',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charlott',
 'charm',
 'chart',
 'chase',
 'chasesandrac',
 'chauffeur',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childhoodmemori',
 'childhoodtrauma',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chinatown',
 'chines',
 'chip',
 'chipmunk',
 'chloe',
 'chocol',
 'choic',
 'choice',
 'choir',
 'chon',
 'choos',
 'chosen',
 'chosenon',
 'chri',
 'christ',
 'christian',
 'christin',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'cigarettesmok',
 'cigarsmok',
 'cindi',
 'cinema',
 'circl',
 'circle',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'coastal',
 'cocain',
 'cocki',
 'code',
 'codi',
 'coffin',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'collaps',
 'collapse',
 'colleagu',
 'colleague',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collide',
 'collis',
 'colombia',
 'colon',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'comicbook',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compound',
 'compromis',
 'compuls',
 'comput',
 'computer',
 'computerviru',
 'conan',
 'concentrationcamp',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'conni',
 'connor',
 'conquer',
 'conquest',
 'conrad',
 'conscienc',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 ...]

In [50]:
ps.stem('actioning')

'action'

In [51]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d'

In [52]:
#Calculating the distance between each movies using cosine distance
#More the angle more will be the dissimilarity b/w the movies
from sklearn.metrics.pairwise import cosine_similarity

In [53]:
similarity=cosine_similarity(vectors)

In [54]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0),
 (1214, 0.281271975231506),
 (539, 0.2694079530401624),
 (3724, 0.2676516895156553),
 (507, 0.2672612419124244),
 (61, 0.2545875386086578),
 (582, 0.25423758993656337),
 (2405, 0.251259453814803),
 (1192, 0.24873416908154547),
 (1202, 0.2457365935914952),
 (778, 0.24310831916315756),
 (4042, 0.23094010767585027),
 (1916, 0.22613350843332272),
 (151, 0.22360679774997894),
 (322, 0.2222222222222222),
 (972, 0.22047927592204916),
 (2782, 0.22047927592204916),
 (172, 0.21821789023599236),
 (74, 0.21650635094610965),
 (2329, 0.21428571428571427),
 (260, 0.2095395190312374),
 (3604, 0.20833333333333331),
 (1087, 0.2049728979374807),
 (495, 0.2041241452319315),
 (4186, 0.2041241452319315),
 (3669, 0.20333142711013955),
 (1440, 0.20211302086361077),
 (3323, 0.20211302086361077),
 (2967, 0.20064308847628196),
 (1199, 0.19999999999999998),
 (305, 0.19867985355975656),
 (373, 0.19641855032959654),
 (2995, 0.19641855032959654),
 (4, 0.19448665533052606),
 (220, 0.19245008972987526),
 (1273, 0.19245008972987526),
 (1327, 0.19245008972987526),
 (4399, 0.19245008972987526),
 (577, 0.19179881852291683),
 (1069, 0.18925832465255626),
 (1319, 0.18633899812498245),
 (83, 0.1849000654084097),
 (27, 0.18463723646899907),
 (168, 0.18446619684315546),
 (47, 0.18325416653445784),
 (2200, 0.18220272220337375),
 (36, 0.1800205749557739),
 (184, 0.1800205749557739),
 (4330, 0.1800205749557739),
 (91, 0.17960530202677488),
 (931, 0.17960530202677488),
 (3993, 0.17960530202677488),
 (41, 0.17588161767036212),
 (300, 0.17588161767036212),
 (942, 0.17588161767036212),
 (661, 0.17507524381296338),
 (1827, 0.17391639824998364),
 (3534, 0.17201561551404665),
 (1978, 0.17149858514250882),
 (595, 0.1701758234142103),
 (529, 0.17017582341421028),
 (342, 0.1677050983124842),
 (1176, 0.16666666666666669),
 (31, 0.16666666666666666),
 (67, 0.16666666666666666),
 (150, 0.16666666666666666),
 (2511, 0.16666666666666666),
 (94, 0.16343011261515333),
 (581, 0.16343011261515333),
 (2727, 0.16343011261515333),
 (1533, 0.1633660098032678),
 (149, 0.16169041669088863),
 (4004, 0.16169041669088863),
 (26, 0.16012815380508713),
 (187, 0.16012815380508713),
 (513, 0.15811388300841897),
 (1379, 0.15811388300841897),
 (275, 0.15748519708717798),
 (838, 0.15713484026367724),
 (7, 0.15617376188860607),
 (52, 0.15617376188860607),
 (111, 0.15617376188860607),
 (311, 0.15617376188860604),
 (294, 0.15474611514754322),
 (568, 0.15474611514754322),
 (127, 0.15294382258037448),
 (1342, 0.15249857033260467),
 (1353, 0.15249857033260467),
 (46, 0.15214515486254612),
 (579, 0.15214515486254612),
 (2071, 0.15214515486254612),
 (95, 0.15075567228888181),
 (108, 0.15075567228888181),
 (1475, 0.15061601901917732),
 (3158, 0.1506160190191773),
 (2756, 0.14937635992171197),
 (1271, 0.14907119849998599),
 (466, 0.14907119849998596),
 (935, 0.14907119849998596),
 (1484, 0.14907119849998596),
 (1392, 0.14816681483355557),
 (1295, 0.14744195615489714),
 (1934, 0.1474419561548971),
 (2492, 0.14731391274719738),
 (1961, 0.14583333333333331),
 (56, 0.14547859349066158),
 (249, 0.14547859349066158),
 (490, 0.14547859349066158),
 (1325, 0.14547859349066158),
 (843, 0.14506471329641488),
 (3350, 0.14506471329641488),
 (4073, 0.14506471329641488),
 (17, 0.14470719035407653),
 (461, 0.14291548761875733),
 (2165, 0.14291548761875733),
 (3405, 0.14291548761875733),
 (476, 0.14213381090374028),
 (487, 0.14213381090374028),
 (3775, 0.14213381090374028),
 (72, 0.14085904245475275),
 (413, 0.14085904245475275),
 (1804, 0.14085904245475275),
 (502, 0.14002800840280097),
 (483, 0.13900960937138318),
 (505, 0.13900960937138318),
 (668, 0.13900960937138318),
 (1369, 0.13900960937138318),
 (3976, 0.13900960937138318),
 (859, 0.1388888888888889),
 (1013, 0.1388888888888889),
 (4532, 0.1386750490563073),
 (777, 0.13736056394868904),
 (14, 0.13699915608779772),
 (1556, 0.13699915608779772),
 (134, 0.13608276348795434),
 (368, 0.13608276348795434),
 (773, 0.13608276348795434),
 (1156, 0.13608276348795434),
 (2374, 0.13608276348795434),
 (2580, 0.13608276348795434),
 (2177, 0.13518451760896877),
 (3618, 0.13518451760896877),
 (2129, 0.13483997249264842),
 (158, 0.1336306209562122),
 (3079, 0.1336306209562122),
 (4342, 0.1336306209562122),
 (126, 0.13344012817090595),
 (68, 0.13333333333333333),
 (1770, 0.13333333333333333),
 (2869, 0.13245323570650439),
 (1320, 0.13209898731686948),
 (138, 0.13176156917368248),
 (754, 0.13176156917368248),
 (1084, 0.13176156917368248),
 (2682, 0.13176156917368248),
 (3624, 0.13176156917368248),
 (4224, 0.13176156917368248),
 (208, 0.13074409009212268),
 (1094, 0.13074409009212268),
 (2056, 0.13074409009212268),
 (438, 0.1301448015738384),
 (937, 0.1301448015738384),
 (2446, 0.1301448015738384),
 (102, 0.12909944487358055),
 (189, 0.12909944487358055),
 (1737, 0.12909944487358055),
 (2785, 0.12909944487358055),
 (166, 0.12858612496840993),
 (549, 0.12858612496840993),
 (1272, 0.12830005981991682),
 (1654, 0.12830005981991682),
 (2966, 0.12830005981991682),
 (84, 0.12803687993289598),
 (678, 0.1259881576697424),
 (781, 0.1259881576697424),
 (1002, 0.1259881576697424),
 (1045, 0.1259881576697424),
 (1874, 0.1259881576697424),
 (2648, 0.1259881576697424),
 (3372, 0.1259881576697424),
 (369, 0.1256297269074015),
 (1571, 0.125),
 (2327, 0.125),
 (2476, 0.125),
 (2670, 0.125),
 (278, 0.12422599874998833),
 (557, 0.12422599874998831),
 (900, 0.12422599874998831),
 (1297, 0.12422599874998831),
 (2280, 0.12422599874998831),
 (122, 0.12379689211803457),
 (3730, 0.12379689211803457),
 (4667, 0.12379689211803457),
 (1000, 0.12309149097933271),
 (182, 0.1228682967957476),
 (1054, 0.1228682967957476),
 (50, 0.1217161238900369),
 (121, 0.1217161238900369),
 (236, 0.1217161238900369),
 (422, 0.1217161238900369),
 (1299, 0.1217161238900369),
 (1829, 0.1217161238900369),
 (2737, 0.1217161238900369),
 (454, 0.12155415958157878),
 (870, 0.12155415958157878),
 (2543, 0.12155415958157878),
 (653, 0.12126781251816647),
 (808, 0.12126781251816647),
 (1346, 0.12126781251816647),
 (1669, 0.12126781251816647),
 (1711, 0.12126781251816647),
 (2319, 0.12126781251816647),
 (3994, 0.12126781251816647),
 (139, 0.12126781251816646),
 (160, 0.12097769771854958),
 (1613, 0.12028130608117205),
 (536, 0.12028130608117203),
 (232, 0.11973686801784994),
 (85, 0.11969747440993465),
 (589, 0.11952286093343936),
 (1493, 0.11952286093343936),
 (1218, 0.11904761904761904),
 (3231, 0.11904761904761904),
 (1497, 0.11785113019775793),
 (3715, 0.11785113019775793),
 (1414, 0.11785113019775792),
 (1508, 0.11785113019775792),
 (3208, 0.11785113019775792),
 (21, 0.1178511301977579),
 (28, 0.1178511301977579),
 (449, 0.1178511301977579),
 (3004, 0.1178511301977579),
 (123, 0.11669000700233413),
 (420, 0.11669000700233413),
 (889, 0.11666666666666667),
 (1612, 0.1160517706371319),
 (228, 0.11556254088025607),
 (432, 0.11556254088025607),
 (5, 0.11556254088025605),
 (1570, 0.11547005383792512),
 (200, 0.11470786693528086),
 (627, 0.11470786693528086),
 (2517, 0.11470786693528086),
 (3143, 0.11470786693528086),
 (4129, 0.11470786693528086),
 (1941, 0.11433239009500587),
 (2068, 0.11433239009500587),
 (3424, 0.11433239009500587),
 (238, 0.11396057645963795),
 (692, 0.11340230290662862),
 (3305, 0.11340230290662862),
 (81, 0.11322770341445956),
 (87, 0.1126872339638022),
 (295, 0.1126872339638022),
 (332, 0.1126872339638022),
 (472, 0.1126872339638022),
 (643, 0.1126872339638022),
 (1029, 0.1126872339638022),
 (4462, 0.1126872339638022),
 (262, 0.11236664374387369),
 (2368, 0.11236664374387369),
 (572, 0.11236664374387367),
 (307, 0.11226255234242723),
 (105, 0.11180339887498947),
 (157, 0.11180339887498947),
 (233, 0.11180339887498947),
 (256, 0.11180339887498947),
 (319, 0.11180339887498947),
 (1520, 0.11180339887498947),
 (1741, 0.11180339887498947),
 (2157, 0.11180339887498947),
 (3051, 0.11180339887498947),
 (3089, 0.11135885079684349),
 (3626, 0.11135885079684349),
 (229, 0.1111111111111111),
 (687, 0.1111111111111111),
 (786, 0.1111111111111111),
 (1235, 0.1111111111111111),
 (1767, 0.1111111111111111),
 (3336, 0.1111111111111111),
 (3494, 0.1111111111111111),
 (4091, 0.1111111111111111),
 (4771, 0.1111111111111111),
 (170, 0.11037769642208699),
 (467, 0.11037769642208699),
 (541, 0.11037769642208699),
 (939, 0.10976425998969033),
 (131, 0.10959932487023819),
 (223, 0.10959932487023819),
 (3833, 0.1091089451179962),
 (33, 0.10910894511799618),
 (1164, 0.10910894511799618),
 (1278, 0.10910894511799618),
 (2452, 0.10910894511799618),
 (2630, 0.10910894511799618),
 (654, 0.10849075915068657),
 (330, 0.10814761408717502),
 (1035, 0.10814761408717502),
 (1193, 0.10814761408717502),
 (2813, 0.10814761408717502),
 (1451, 0.10758287072798378),
 (1492, 0.10758287072798378),
 (2102, 0.10758287072798378),
 (75, 0.10675210253672475),
 (207, 0.10675210253672475),
 (1292, 0.10675210253672475),
 (2494, 0.10669739994407998),
 (35, 0.10660035817780521),
 (624, 0.10660035817780521),
 (2758, 0.10660035817780521),
 (3617, 0.10660035817780521),
 (3948, 0.10660035817780521),
 (445, 0.10540925533894598),
 (508, 0.10540925533894598),
 (3630, 0.10540925533894598),
 (3749, 0.10540925533894598),
 (3868, 0.10540925533894598),
 (3437, 0.104990131391452),
 (1401, 0.10499013139145198),
 (1435, 0.10499013139145198),
 (878, 0.10425720702853739),
 (1154, 0.10425720702853739),
 (1938, 0.10425720702853739),
 (2558, 0.10425720702853739),
 (3657, 0.10425720702853739),
 (4325, 0.10425720702853739),
 (10, 0.10411584125907071),
 (510, 0.10411584125907071),
 (986, 0.10411584125907071),
 (1080, 0.10411584125907071),
 (1610, 0.10411584125907071),
 (2144, 0.10411584125907071),
 (3148, 0.10411584125907071),
 (363, 0.10336227882434039),
 (2435, 0.10336227882434039),
 (266, 0.10286889997472794),
 (312, 0.10286889997472794),
 (334, 0.10286889997472794),
 (480, 0.10286889997472794),
 (535, 0.10286889997472794),
 (898, 0.10286889997472794),
 (1397, 0.10286889997472794),
 (2237, 0.10286889997472794),
 (1771, 0.10257624248277726),
 (263, 0.10206207261596575),
 (362, 0.10206207261596575),
 (511, 0.10206207261596575),
 (660, 0.10206207261596575),
 (715, 0.10206207261596575),
 (1025, 0.10206207261596575),
 (1075, 0.10206207261596575),
 (1880, 0.10206207261596575),
 (2049, 0.10206207261596575),
 (3533, 0.10206207261596575),
 (4012, 0.10206207261596575),
 (4484, 0.10206207261596575),
 (2095, 0.10180787029692101),
 (9, 0.10166571355506977),
 (371, 0.10166571355506977),
 (1819, 0.10166571355506977),
 (2243, 0.10166571355506977),
 (3616, 0.10166571355506977),
 (3929, 0.10166571355506977),
 (412, 0.10050378152592121),
 (534, 0.10050378152592121),
 (2249, 0.10050378152592121),
 (491, 0.10032154423814099),
 (356, 0.1),
 (791, 0.1),
 (1717, 0.1),
 (1723, 0.1),
 (2783, 0.1),
 (4192, 0.1),
 (4397, 0.1),
 (4466, 0.1),
 (18, 0.09960238411119947),
 (206, 0.09950371902099889),
 (11, 0.09938079899999065),
 (814, 0.09938079899999065),
 (1107, 0.09938079899999065),
 (3777, 0.09938079899999065),
 (410, 0.09829463743659808),
 (1688, 0.09829463743659808),
 (2484, 0.09829463743659808),
 (2552, 0.09829463743659808),
 (2816, 0.09829463743659808),
 (12, 0.09805806756909201),
 (148, 0.09805806756909201),
 (219, 0.09805806756909201),
 (244, 0.09805806756909201),
 (325, 0.09805806756909201),
 (389, 0.09805806756909201),
 (1752, 0.09805806756909201),
 (4197, 0.09805806756909201),
 (4250, 0.09805806756909201),
 (301, 0.0975342893301088),
 (243, 0.09724332766526303),
 (473, 0.09724332766526303),
 (2588, 0.09724332766526303),
 (785, 0.09687303228651606),
 (4539, 0.09687303228651606),
 (813, 0.09622504486493763),
 (1274, 0.09622504486493763),
 (1355, 0.09622504486493763),
 (1442, 0.09622504486493763),
 (1660, 0.09622504486493763),
 (2876, 0.09622504486493763),
 (3714, 0.09622504486493763),
 (4496, 0.09622504486493763),
 (167, 0.09622504486493762),
 (564, 0.09622504486493762),
 (920, 0.09622504486493762),
 (978, 0.09622504486493762),
 (1304, 0.09622504486493762),
 (1470, 0.09622504486493762),
 (1569, 0.09622504486493762),
 (1682, 0.09622504486493762),
 (2089, 0.09622504486493762),
 (2247, 0.09622504486493762),
 (2392, 0.09622504486493762),
 (2641, 0.09622504486493762),
 (230, 0.09558988911273406),
 (239, 0.09558988911273406),
 (799, 0.09558988911273406),
 (596, 0.09523809523809523),
 (602, 0.09523809523809523),
 (995, 0.09523809523809523),
 (1697, 0.09523809523809523),
 (1992, 0.09523809523809523),
 (2646, 0.09523809523809523),
 (23, 0.0944911182523068),
 (400, 0.0944911182523068),
 (1140, 0.0944911182523068),
 (1476, 0.0944911182523068),
 (2647, 0.0944911182523068),
 (2953, 0.0944911182523068),
 (3445, 0.0944911182523068),
 (2566, 0.09435641951204964),
 (43, 0.09428090415820634),
 (270, 0.09428090415820634),
 (1842, 0.09428090415820634),
 (3385, 0.09428090415820634),
 (3403, 0.09428090415820634),
 (3875, 0.09428090415820634),
 (331, 0.09335200560186731),
 (1231, 0.09335200560186731),
 (1779, 0.09335200560186731),
 (88, 0.09284766908852593),
 (457, 0.09284766908852593),
 (1247, 0.09284766908852593),
 (1257, 0.09284766908852593),
 (1585, 0.09284766908852593),
 (2656, 0.09284766908852593),
 (2864, 0.09284766908852593),
 (3444, 0.09284766908852593),
 (169, 0.09245003270420485),
 (752, 0.09245003270420485),
 (1526, 0.09245003270420485),
 (1694, 0.09245003270420485),
 (2359, 0.09245003270420485),
 (2852, 0.09245003270420485),
 (3176, 0.09245003270420485),
 (3458, 0.09245003270420485),
 (4347, 0.09245003270420485),
 (618, 0.09157370929912602),
 (1902, 0.09157370929912602),
 (1, 0.09128709291752768),
 (2, 0.09128709291752768),
 (141, 0.09128709291752768),
 (203, 0.09128709291752768),
 (292, 0.09128709291752768),
 (3318, 0.09128709291752768),
 (274, 0.09110136110168686),
 (479, 0.0909241209316635),
 (2111, 0.0909241209316635),
 (740, 0.09072184232530289),
 (1017, 0.09072184232530289),
 (2709, 0.09072184232530289),
 (2736, 0.09072184232530289),
 (4337, 0.09072184232530289),
 (129, 0.08989331499509895),
 (143, 0.08989331499509895),
 (234, 0.08989331499509895),
 (827, 0.08989331499509895),
 (3549, 0.08989331499509895),
 (142, 0.08980265101338746),
 (745, 0.08980265101338746),
 (960, 0.08980265101338746),
 (1684, 0.08980265101338746),
 (1095, 0.08980265101338744),
 (2444, 0.08934271123648291),
 (32, 0.0890870806374748),
 (199, 0.0890870806374748),
 (217, 0.0890870806374748),
 (381, 0.0890870806374748),
 (1303, 0.0890870806374748),
 (1828, 0.0890870806374748),
 (2335, 0.0890870806374748),
 (2792, 0.0890870806374748),
 (3552, 0.0890870806374748),
 (4510, 0.0890870806374748),
 (4581, 0.0890870806374748),
 (315, 0.08838834764831843),
 (341, 0.08838834764831843),
 (2579, 0.08838834764831843),
 (3131, 0.08838834764831843),
 (3297, 0.08838834764831843),
 (48, 0.08830215713766959),
 (190, 0.08753762190648169),
 (2350, 0.08753762190648169),
 (152, 0.08703882797784893),
 (227, 0.08703882797784893),
 (775, 0.08703882797784893),
 (894, 0.08703882797784893),
 (901, 0.08703882797784893),
 (1267, 0.08703882797784893),
 (4748, 0.08703882797784893),
 (1635, 0.08679260732054925),
 (2964, 0.08679260732054925),
 (62, 0.08606629658238703),
 (403, 0.08606629658238703),
 (584, 0.08606629658238703),
 (776, 0.08606629658238703),
 (850, 0.08606629658238703),
 (866, 0.08606629658238703),
 (1003, 0.08606629658238703),
 (3214, 0.08606629658238703),
 (3972, 0.08606629658238703),
 (4731, 0.08606629658238703),
 (37, 0.08574929257125441),
 (242, 0.08574929257125441),
 (547, 0.08574929257125441),
 (1205, 0.08574929257125441),
 (1745, 0.08574929257125441),
 (2124, 0.08574929257125441),
 (2300, 0.08574929257125441),
 (3136, 0.08574929257125441),
 (3466, 0.08574929257125441),
 (4554, 0.08574929257125441),
 (501, 0.08535791995526398),
 (19, 0.08466675133346033),
 (96, 0.08451542547285165),
 (164, 0.08451542547285165),
 (245, 0.08451542547285165),
 (306, 0.08451542547285165),
 (329, 0.08451542547285165),
 (626, 0.08451542547285165),
 (1287, 0.08451542547285165),
 (1515, 0.08451542547285165),
 (2163, 0.08451542547285165),
 (2215, 0.08451542547285165),
 (2657, 0.08451542547285165),
 (38, 0.08399210511316159),
 (45, 0.08399210511316159),
 (812, 0.08399210511316159),
 (2199, 0.08399210511316159),
 (2382, 0.08375315127160099),
 (16, 0.08333333333333333),
 (112, 0.08333333333333333),
 (402, 0.08333333333333333),
 (737, 0.08333333333333333),
 (899, 0.08333333333333333),
 (1517, 0.08333333333333333),
 (1530, 0.08333333333333333),
 (1743, 0.08333333333333333),
 (2475, 0.08333333333333333),
 (2667, 0.08333333333333333),
 (2861, 0.08333333333333333),
 (2873, 0.08333333333333333),
 (3098, 0.08333333333333333),
 (3523, 0.08333333333333333),
 (3920, 0.08333333333333333),
 (4159, 0.08333333333333333),
 (4486, 0.08333333333333333),
 (4562, 0.08333333333333333),
 (4620, 0.08333333333333333),
 (4635, 0.08333333333333333),
 (4648, 0.08333333333333333),
 (4651, 0.08333333333333333),
 (486, 0.08291976585083241),
 (63, 0.08268982305947231),
 (222, 0.08268982305947231),
 (1922, 0.08268982305947231),
 (39, 0.08219949365267865),
 (70, 0.08219949365267865),
 (71, 0.08219949365267865),
 (101, 0.08219949365267865),
 (174, 0.08219949365267865),
 (349, 0.08219949365267865),
 (632, 0.08219949365267865),
 (787, 0.08219949365267865),
 (854, 0.08219949365267865),
 (922, 0.08219949365267865),
 (1078, 0.08219949365267865),
 (1159, 0.08219949365267865),
 (1323, 0.08219949365267865),
 (2640, 0.08219949365267865),
 (2679, 0.08219949365267865),
 (3810, 0.08219949365267865),
 (4335, 0.08219949365267865),
 (153, 0.08206099398622181),
 (2788, 0.08206099398622181),
 (3899, 0.08206099398622181),
 (103, 0.08144629623753681),
 (193, 0.08132500607904443),
 (40, 0.08111071056538127),
 (210, 0.08111071056538127),
 (3229, 0.08111071056538127),
 (4310, 0.08111071056538127),
 (286, 0.08084520834544431),
 (993, 0.08084520834544431),
 (1137, 0.08084520834544431),
 (1321, 0.08084520834544431),
 (3122, 0.08084520834544431),
 (3426, 0.08084520834544431),
 (3722, 0.08084520834544431),
 (3826, 0.08084520834544431),
 (4273, 0.08084520834544431),
 (4467, 0.08084520834544431),
 (4500, 0.08084520834544431),
 (1824, 0.0802572353905128),
 (1920, 0.0802572353905128),
 (3556, 0.0802572353905128),
 (241, 0.08006407690254357),
 (365, 0.08006407690254357),
 (634, 0.08006407690254357),
 (680, 0.08006407690254357),
 (885, 0.08006407690254357),
 (1007, 0.08006407690254357),
 (1519, 0.08006407690254357),
 (2934, 0.08006407690254357),
 (3024, 0.08006407690254357),
 (3087, 0.08006407690254357),
 (3160, 0.08006407690254357),
 (246, 0.07968190728895957),
 (1655, 0.07911877721292354),
 (98, 0.07905694150420949),
 (361, 0.07905694150420949),
 (503, 0.07905694150420949),
 (794, 0.07905694150420949),
 (1111, 0.07905694150420949),
 (1363, 0.07905694150420949),
 (2159, 0.07905694150420949),
 (2291, 0.07905694150420949),
 (3758, 0.07905694150420949),
 (4039, 0.07905694150420949),
 (4262, 0.07905694150420949),
 (4552, 0.07905694150420949),
 (4618, 0.07905694150420949),
 (125, 0.07881104062391006),
 (205, 0.07856742013183862),
 (800, 0.07856742013183862),
 (1252, 0.07856742013183862),
 (1617, 0.07856742013183862),
 (1651, 0.07856742013183862),
 (2001, 0.07856742013183862),
 (2110, 0.07856742013183862),
 (2270, 0.07856742013183862),
 (2313, 0.07856742013183862),
 (2322, 0.07856742013183862),
 (2377, 0.07856742013183862),
 (2708, 0.07856742013183862),
 (3068, 0.07856742013183862),
 (3151, 0.07856742013183862),
 (3479, 0.07856742013183862),
 (82, 0.07808688094430304),
 (492, 0.07808688094430304),
 (540, 0.07808688094430304),
 (1068, 0.07808688094430304),
 (1619, 0.07808688094430304),
 (2445, 0.07808688094430304),
 (2984, 0.07808688094430304),
 (2252, 0.07802743146408704),
 (1280, 0.07749842582921285),
 (235, 0.07715167498104596),
 (1288, 0.07715167498104596),
 (1291, 0.07715167498104596),
 (2017, 0.07715167498104596),
 (3695, 0.07715167498104596),
 (3845, 0.07715167498104596),
 (4199, 0.07715167498104596),
 (3327, 0.0770416939201707),
 (51, 0.07698003589195009),
 (100, 0.07647191129018724),
 (1406, 0.07647191129018724),
 (1766, 0.07647191129018724),
 (1986, 0.07647191129018724),
 (2208, 0.07647191129018724),
 (2547, 0.07647191129018724),

In [55]:
def recommend(movie):
    movie_index=new_data[new_data['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_data.iloc[i[0]].title)

In [56]:
recommend('Avatar')

Aliens vs Predator: Requiem
Titan A.E.
Falcon Rising
Independence Day
Jupiter Ascending

In [57]:
recommend('Batman Begins')

The Dark Knight
Batman
10th & Wolf
Batman v Superman: Dawn of Justice
Synecdoche, New York